name: Continuous Deployment (CD) to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Vercel CLI
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Adicione seu token Vercel nos Secrets
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  # Adicione seu org ID Vercel nos Secrets
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # Adicione seu project ID Vercel nos Secrets
        vercel-args: '--prod'  # Envia para o ambiente de produção
