name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests (se houver)
      run: npm test # Caso haja testes, substitua com o comando correto

    - name: Build Docker image
      run: docker build -t my-app .

    - name: Run Docker container
      run: docker run -d -p 3000:3000 my-app
